typography_spectrum: 0.00326
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#6da0a9'
    - '#e82116'
    - '#44fece'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.76301
analytics:
  google: UA-73555765-1
  facebook: null
  twitter: null
name: Jamie Barlow
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Barlows
purpose: []
