name: Jamie Barlow
favicon: null
layout_spectrum: 0.72601
typography_spectrum: 0.61732
title: Jamie Barlow
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73555765-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1494a9'
    - '#95c613'
    - '#1da1b8'
    - '#41bdd1'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
