name: Jamie Barlow
favicon: null
layout_spectrum: 0.72601
typography_spectrum: 0.61732
title: Jamie Barlow
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-55286287-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ED6C00'
    - '#FAF800'
    - '#83BA00'
    - '#2398F5'
    - '#754EA0'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
