name: Jamie Barlow
favicon: null
layout_spectrum: 0.98868
typography_spectrum: 0.31118
title: Jamie Barlow
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-55286287-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040205'
    - '#fefefc'
    - '#5f3c54'
    - '#e37447'
    - '#017e75'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
